apiVersion: v1
kind: DeploymentConfig
metadata:
  name: wso2-mgw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: wso2-mgw
    spec:
      containers:
      - name: wso2ei-server
        image: 172.30.139.20:5000/wso2/wso2-mgw:0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 802
          fsGroup: 802
        ports:
        - containerPort: 9090
          protocol: TCP
        - containerPort: 9095
          protocol: TCP
      serviceAccountName: "wso2svc-acct"
