apiVersion: v1
kind: Service
metadata:
  name: wso2-gw
spec:
  type: ClusterIP
  selector:
    deploymentconfig: wso2-mgw
  ports:
  - name: carbon-port
    port: 9090
    targetPort: 9090
    protocol: TCP
