apiVersion: v1
kind: Service
metadata:
  name: wso2-mi
spec:
  type: ClusterIP
  selector:
    deploymentconfig: wso2-mi
  ports:
  - name: carbon-port
    port: 8290
    targetPort: 8290
    protocol: TCP
